In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [5]:
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(indep,dep,test_size=0.30,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [22]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'n_neighbors' :[4,5] , 'weights' : ['uniform', 'distance'],
         'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],
           'p':[2],'metric':['minkowski']
           }
grid=GridSearchCV(KNeighborsClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')

grid.fit(x_train,y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\Users\ELCOT\.eclipse\anaconda\lib\site-packages\sklearn\neighbors\_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski'], 'n_neighbors': [4, 5],
                         'p': [2], 'weights': ['uniform', 'distance']},
             scoring='f1_weighted', verbose=3)

In [23]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.209350,0.237474,0.356392,0.347787,auto,minkowski,4,2,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.929513,0.964572,0.929513,0.964572,0.963912,0.950416,0.01707,13
1,0.040922,0.035667,0.103498,0.031973,auto,minkowski,4,2,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.964572,0.982221,0.929513,0.964572,1.000000,0.968176,0.02337,1
2,0.043602,0.024832,0.109499,0.019754,auto,minkowski,5,2,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.964572,0.964572,0.929513,0.964572,0.963912,0.957428,0.01396,9
3,0.023884,0.007045,0.067021,0.006170,auto,minkowski,5,2,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.964572,0.982221,0.929513,0.964572,0.963912,0.960958,0.01718,5
4,0.037771,0.044297,0.059383,0.015313,ball_tree,minkowski,4,2,uniform,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.929513,0.964572,0.929513,0.964572,0.963912,0.950416,0.01707,13
5,0.021881,0.007655,0.037500,0.007656,ball_tree,minkowski,4,2,distance,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.964572,0.982221,0.929513,0.964572,1.000000,0.968176,0.02337,1
6,0.015629,0.000011,0.046874,0.000007,ball_tree,minkowski,5,2,uniform,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.964572,0.964572,0.929513,0.964572,0.963912,0.957428,0.01396,9
7,0.015625,0.009881,0.037504,0.007656,ball_tree,minkowski,5,2,distance,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.964572,0.982221,0.929513,0.964572,0.963912,0.960958,0.01718,5
8,0.027648,0.011191,0.055578,0.017291,kd_tree,minkowski,4,2,uniform,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.929513,0.964572,0.929513,0.964572,0.963912,0.950416,0.01707,13
9,0.035382,0.012403,0.066840,0.008955,kd_tree,minkowski,4,2,distance,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.964572,0.982221,0.929513,0.964572,1.000000,0.968176,0.02337,1
10,0.083071,0.060590,0.090020,0.007851,kd_tree,minkowski,5,2,uniform,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.964572,0.964572,0.929513,0.964572,0.963912,0.957428,0.01396,9
11,0.027360,0.014021,0.047827,0.011046,kd_tree,minkowski,5,2,distance,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.964572,0.982221,0.929513,0.964572,0.963912,0.960958,0.01718,5
12,0.020951,0.006685,0.073401,0.006271,brute,minkowski,4,2,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.929513,0.964572,0.929513,0.964572,0.963912,0.950416,0.01707,13
13,0.025971,0.014233,0.132884,0.040097,brute,minkowski,4,2,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.964572,0.982221,0.929513,0.964572,1.000000,0.968176,0.02337,1
14,0.043837,0.012410,0.148750,0.040013,brute,minkowski,5,2,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.964572,0.964572,0.929513,0.964572,0.963912,0.957428,0.01396,9
15,0.010998,0.006225,0.072636,0.008391,brute,minkowski,5,2,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.964572,0.982221,0.929513,0.964572,0.963912,0.960958,0.01718,5

In [24]:
bestParams=grid.best_params_
print("Best Parameter {} ".format(bestParams))

Best Parameter {'algorithm': 'auto', 'metric': 'minkowski', 'n_neighbors': 4, 'p': 2, 'weights': 'distance'}

In [25]:
gridPred=grid.predict(x_test)

In [26]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,gridPred)
print(cm)

[[45  0]
 [ 3 72]]

In [27]:
from sklearn.metrics import classification_report
clf=classification_report(y_test,gridPred)
print(clf)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        45
           1       1.00      0.96      0.98        75

    accuracy                           0.97       120
   macro avg       0.97      0.98      0.97       120
weighted avg       0.98      0.97      0.98       120

In [28]:
from sklearn.metrics import f1_score
fscore=f1_score(y_test,gridPred,average='weighted')
print(fscore)

0.9751481237656352

In [29]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

1.0

In [30]:
age=int(input("Age : "))
bp=float(input("BP : "))
al=float(input("AL : "))
su=float(input("su : "))
bgr=float(input("bgr : "))
bu=float(input("bu : "))
sc=float(input("sc : "))
sod=float(input("sod : "))
pot=float(input("pot : "))
hrmo=float(input("hrmo : "))
pcv=int(input("pcv : "))
wc=int(input("wc : "))
rc=int(input("rc : "))
sg_b=int(input("sg_b : "))
sg_c=int(input("sg_c : "))
sg_d=int(input("sg_d : "))
sg_e=int(input("sg_e : "))
rbc_normal=int(input("rbc_normal : "))
pc_normal=int(input("pc_normal : "))
pcc_present=int(input("pcc_present : "))
ba_present=int(input("ba_present : "))
htn_yes=int(input("htn_yes : "))
dm_yes=int(input("dm_yes : "))
cad_yes=int(input("cad_yes : "))
appet_yes=int(input("appet_yes : "))
pe_yes=int(input("pe_yes : "))
ane_yes=int(input("Ane_yes : "))

Age : 13
BP : 4.3
AL : 2.4
su : 5.6
bgr : 8.9
bu : 5.89
sc : 3.2
sod : 1.567
pot : 4.678
hrmo : 6.98
pcv : 5
wc : 7
rc : 6
sg_b : 1
sg_c : 0
sg_d : 0
sg_e : 0
rbc_normal : 1
pc_normal : 1
pcc_present : 1
ba_present : 0
htn_yes : 0
dm_yes : 1
cad_yes : 1
appet_yes : 0
pe_yes : 1
Ane_yes : 1

In [31]:
futurePred=grid.predict([[age,bp,al,su, bgr, bu, sc, sod, pot, hrmo, pcv,
       wc, rc, sg_b, sg_c, sg_d, sg_e, rbc_normal, pc_normal,
       pcc_present, ba_present, htn_yes, dm_yes, cad_yes,
       appet_yes, pe_yes, ane_yes]])
print("Future Predictions : {} ".format(futurePred))

Future Predictions : [1]