In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [5]:
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(indep,dep,test_size=0.30,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [13]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV
param_grid={ 'alpha' : [1.1,1.2,2.5],
            'force_alpha' : [0,1]
           }
grid=GridSearchCV(BernoulliNB(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')

grid.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

C:\Users\ELCOT\.eclipse\anaconda\lib\site-packages\sklearn\utils\_param_validation.py:591: FutureWarning: Passing an int for a boolean parameter is deprecated in version 1.2 and won't be supported anymore in version 1.4.
  warnings.warn(
C:\Users\ELCOT\.eclipse\anaconda\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=BernoulliNB(), n_jobs=-1,
             param_grid={'alpha': [1.1, 1.2, 2.5], 'force_alpha': [0, 1]},
             scoring='f1_weighted', verbose=3)

In [14]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_force_alpha,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.070704,0.062935,0.052245,0.015244,1.1,0,"{'alpha': 1.1, 'force_alpha': 0}",1.000000,1.000000,0.964572,0.982221,1.0,0.989359,0.014178,1
1,0.018751,0.006251,0.040631,0.007658,1.1,1,"{'alpha': 1.1, 'force_alpha': 1}",1.000000,1.000000,0.964572,0.982221,1.0,0.989359,0.014178,1
2,0.015624,0.000003,0.031252,0.000004,1.2,0,"{'alpha': 1.2, 'force_alpha': 0}",1.000000,1.000000,0.964572,0.982221,1.0,0.989359,0.014178,1
3,0.018752,0.006247,0.037501,0.007651,1.2,1,"{'alpha': 1.2, 'force_alpha': 1}",1.000000,1.000000,0.964572,0.982221,1.0,0.989359,0.014178,1
4,0.019262,0.006080,0.034484,0.006201,2.5,0,"{'alpha': 2.5, 'force_alpha': 0}",0.982221,0.982221,0.947015,0.982221,1.0,0.978736,0.017291,5
5,0.028080,0.013057,0.032579,0.009825,2.5,1,"{'alpha': 2.5, 'force_alpha': 1}",0.982221,0.982221,0.947015,0.982221,1.0,0.978736,0.017291,5

In [15]:
bestParams=grid.best_params_
print("Best Parameter {} ".format(bestParams))

Best Parameter {'alpha': 1.1, 'force_alpha': 0}

In [16]:
gridPred=grid.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,gridPred)
print(cm)

[[45  0]
 [ 3 72]]

In [18]:
from sklearn.metrics import classification_report
clf=classification_report(y_test,gridPred)
print(clf)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        45
           1       1.00      0.96      0.98        75

    accuracy                           0.97       120
   macro avg       0.97      0.98      0.97       120
weighted avg       0.98      0.97      0.98       120

In [19]:
from sklearn.metrics import f1_score
fscore=f1_score(y_test,gridPred,average='weighted')
print(fscore)

0.9751481237656352

In [20]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

1.0

In [21]:
age=int(input("Age : "))
bp=float(input("BP : "))
al=float(input("AL : "))
su=float(input("su : "))
bgr=float(input("bgr : "))
bu=float(input("bu : "))
sc=float(input("sc : "))
sod=float(input("sod : "))
pot=float(input("pot : "))
hrmo=float(input("hrmo : "))
pcv=int(input("pcv : "))
wc=int(input("wc : "))
rc=int(input("rc : "))
sg_b=int(input("sg_b : "))
sg_c=int(input("sg_c : "))
sg_d=int(input("sg_d : "))
sg_e=int(input("sg_e : "))
rbc_normal=int(input("rbc_normal : "))
pc_normal=int(input("pc_normal : "))
pcc_present=int(input("pcc_present : "))
ba_present=int(input("ba_present : "))
htn_yes=int(input("htn_yes : "))
dm_yes=int(input("dm_yes : "))
cad_yes=int(input("cad_yes : "))
appet_yes=int(input("appet_yes : "))
pe_yes=int(input("pe_yes : "))
ane_yes=int(input("Ane_yes : "))

Age : 14
BP : 3.5
AL : 5.6
su : 6.4
bgr : 9.4
bu : 3.5
sc : 6.3
sod : 2.65
pot : 3.56
hrmo : 7.45
pcv : 7
wc : 8
rc : 5
sg_b : 1
sg_c : 0
sg_d : 1
sg_e : 0
rbc_normal : 1
pc_normal : 0
pcc_present : 1
ba_present : 0
htn_yes : 1
dm_yes : 0
cad_yes : 1
appet_yes : 0
pe_yes : 1
Ane_yes : 1

In [22]:
futurePred=grid.predict([[age,bp,al,su, bgr, bu, sc, sod, pot, hrmo, pcv,
       wc, rc, sg_b, sg_c, sg_d, sg_e, rbc_normal, pc_normal,
       pcc_present, ba_present, htn_yes, dm_yes, cad_yes,
       appet_yes, pe_yes, ane_yes]])
print("Future Predictions : {} ".format(futurePred))

Future Predictions : [1]